### ISSUE TITLE
Allow adding of users from the SCIM API that aren’t yet in ColdFront

### ISSUE THREAD

**Issue by knikolla** [nerc-project/coldfront-plugin-api#10]
In the current flow of using ColdFront through the web browser, a PI and all members of a project register through RegApp, which creates for them an account in Keycloak. Afterwards the PI logs in to ColdFront with their institutional account and requests PI status, creates a project, resource allocation, and then adds users to the project through a search box. The search box finds users that are registered with the NERC Keycloak even though ColdFront is unaware of them since they haven’t logged in to it.

#9 that merged today, allows adding/removing users that are present in ColdFront. However it is unlikely that normal members log in to ColdFront since it doesn’t provide them any functionality, but just register through RegApp. 

1. Every user needs to have signed the Terms of Service, which we are currently handling through the manual registration process and email verification in RegApp. Therefore, with the current state of the system, we can only allow adding users that exist in Keycloak.
2. The username of users may unfortunately be different from the email address, as currently RegApp allows that flexibility. Therefore the SCIM API needs to allow a mechanism for resolving usernames for email, as I’m assuming PIs will have a list of emails rather than usernames.
3. The solution shouldn’t make API requests directly to Keycloak, but should make use of the functionality of ColdFront to search for users, which we have already extended through https://github.com/nerc-project/coldfront-plugin-keycloak

Solution
- [x] Connect the Groups API from #9 to the user functions above to allow adding Keycloak users to project. -> #12 
- [x] Implement list users -> #13
- [ ] Implement searching users via email
- [x] Implement getting information for a specific user -> #13

**Comment by joachimweyl** [comment]
@knikolla have we had a chance to implement the last step I see "Implement searching users via email"
